AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2LAunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      AssociatePublicIpAddress: true
      ImageId: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: !Ref MufInstanceType
      KeyName: !Ref MufKeyName
      SecurityGroups:
        - !Ref EC2SG
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c9902027-40b9-402e-9164-1d0f6f5ee1fe

Parameters:
  MufVPCID:
    Type: 'AWS::EC2::VPC::Id'
  MufInstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  MufKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  EC2SG:
    Type: String
    Description: SG for the EC2 instances

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0323c3dd2da7fb37d

Outputs:
  RefEC2LAunchConfig:
    Description: Ref of EC2LAunchConfig
    Value: !Ref EC2LAunchConfig