AWSTemplateFormatVersion: 2010-09-09
Resources:
  MainInternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:          
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref MainInternetGateway
      VpcId: !Ref VPCID

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainInternetGateway

#----------------------------    
  NATGatewaySubnet1:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId:
          Fn::GetAtt:
          - EIPForNATGateway1
          - AllocationId
        SubnetId:
          Ref: PublicSubnet1
  EIPForNATGateway1:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
        Domain: "vpc"
        Tags:
          - Key: "Chargable"
            Value: "Yes"
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGatewaySubnet1

#----------------------------      
  NATGatewaySubnet2:
      Type: AWS::EC2::NatGateway
      Properties:
          AllocationId:
            Fn::GetAtt:
            - EIPForNATGateway2
            - AllocationId
          SubnetId:
            Ref: PublicSubnet2
  EIPForNATGateway2:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
        Domain: "vpc"
        Tags:
          - Key: "Chargable"
            Value: "Yes"
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGatewaySubnet2             

Parameters:
  VPCID:
    Description: VPC ID
    Type: String  
  PublicSubnet1:
    Description: Public Subnet 1 ID
    Type: String
  PublicSubnet2:
    Description: Public Subnet 2 ID
    Type: String

Outputs:
  MainInternetGateway:
    Description: NAT Gateway for Subnet1
    Value: !Ref MainInternetGateway
  NATGatewaySubnet1:
    Description: NAT Gateway for Subnet1
    Value: !Ref NATGatewaySubnet1
  NATGatewaySubnet2:
    Description: NAT Gateway for Subnet2
    Value: !Ref NATGatewaySubnet2
  EIPForNATGateway1:
    Description: EIP For NAT Gateway 1
    Value: !Ref EIPForNATGateway1
  EIPForNATGateway2:
    Description: EIP For NAT Gateway 2
    Value: !Ref EIPForNATGateway2    